DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS song;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cookie TEXT UNIQUE NOT NULL,
  preference INTEGER NOT NULL
);

CREATE TABLE song (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  album TEXT NOT NULL,
  uri TEXT NOT NULL
);